---@type LazySpec
return {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
        -- add more things to the ensure_installed table protecting against community packs modifying it
        opts.ensure_installed = require("astrocore").list_insert_unique(opts.ensure_installed, {
            "bash",
            "bibtex",
            "c",
            "cmake",
            "comment",
            "cpp",
            "c_sharp",
            "css",
            "dockerfile",
            "gitcommit",
            "git_config",
            "gitignore",
            "git_rebase",
            "go",
            "haskell",
            "html",
            "http",
            "javascript",
            "jq",
            "json",
            "latex",
            "lua",
            "make",
            "nix",
            "python",
            "regex",
            "rust",
            "rust",
            "toml",
            "toml",
            "tsx",
            "typescript",
            "vim",
            "yaml",
        })
    end,
}
